services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: tesis
      POSTGRES_PASSWORD: tesis2026
      POSTGRES_DB: tesis_dashboard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/postgresql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

volumes:
  pgdata:
